# Generated by Django 4.1 on 2022-08-17 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authwiki', '0002_rename_library_comments_authwiki'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authwiki',
            name='example_instruction',
        ),
        migrations.RemoveField(
            model_name='authwiki',
            name='github_link',
        ),
    ]
